using System;
using System.Collections.Generic;
using System.IO;

namespace GSOOffline
{
    [Serializable]
    public class LootDrop
    {
        public int typeId;
        public string name;
        public int min = 1, max = 1;
        public float chance;
        public List<int> levels = new List<int>();   // empty = every level of this NPC
    }

    [Serializable]
    public class LootMonster
    {
        public string name;
        public bool dropsSilver;
        public List<int> silver = new List<int>();   // [min, max] from the wiki, empty = CombatRules.SilverDrop
        public List<LootDrop> drops = new List<LootDrop>();
    }

    [Serializable]
    public class LootGlobal
    {
        public int typeId;
        public string name;
        public int minLevel, maxLevel;
        public float chance;
    }

    [Serializable]
    public class LootFile
    {
        public List<LootGlobal> global = new List<LootGlobal>();
        public List<LootMonster> monsters = new List<LootMonster>();
    }

    /// <summary>
    /// NPC drop tables from Data/loot.json, generated by GSODevTools/tools/datamining/gen_loot.py from the
    /// community wiki (the server's own tables are lost). Monsters are matched by NPCInfo name.
    /// </summary>
    internal static class LootData
    {
        private static LootFile file;
        private static Dictionary<string, LootMonster> byName;

        public static LootFile File
        {
            get
            {
                if (file != null) return file;
                using (var s = typeof(LootData).Assembly.GetManifestResourceStream("GSOOffline.loot.json"))
                using (var r = new StreamReader(s))
                    file = Json.Deserialize<LootFile>(r.ReadToEnd());
                byName = new Dictionary<string, LootMonster>(StringComparer.OrdinalIgnoreCase);
                foreach (var m in file.monsters) byName[m.name.Trim()] = m;
                Plugin.Log.LogInfo($"[loot] {file.monsters.Count} monster drop tables, {file.global.Count} global drops");
                return file;
            }
        }

        /// <summary>The wiki's table for this NPC name, or null if the wiki has none.</summary>
        public static LootMonster For(string npcName)
        {
            if (File == null || string.IsNullOrEmpty(npcName)) return null;
            return byName.TryGetValue(npcName.Trim(), out var m) ? m : null;
        }
    }
}
