using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace GSOOffline
{
    [Serializable]
    public class DoorDef
    {
        public int type, scene, toScene;
        public float[] pos, toPos;
        public string note;
    }

    [Serializable]
    public class InteriorDef
    {
        public int scene, interior;
    }

    [Serializable]
    public class SpawnDef
    {
        public int scene;
        public float[] pos;
    }

    [Serializable]
    public class DoorFile
    {
        public List<DoorDef> doors = new List<DoorDef>();
        public List<InteriorDef> interiors = new List<InteriorDef>();
        public List<SpawnDef> interiorSpawns = new List<SpawnDef>();
        public SpawnDef portal;
    }

    [Serializable]
    public class ReturnPoint
    {
        public int scene;
        public float x, y, z;
    }

    /// <summary>
    /// Doors, interiors, portals and the bank. Door destinations come from Data/doors.json, generated by
    /// GSODevTools/tools/datamining/gen_doors.py from the scene markers (the server's own door table is lost).
    /// </summary>
    public partial class OfflineServer
    {
        private const int DoorInterior = 29, DoorInteriorExit = 28, DoorGeneric = 37, InteractChest = 43;
        private const int WindowBank = 14;
        private static DoorFile doorData;

        private static Vector3 V(float[] a) => new Vector3(a[0], a[1], a[2]);

        private static DoorFile Doors
        {
            get
            {
                if (doorData != null) return doorData;
                using (var s = typeof(OfflineServer).Assembly.GetManifestResourceStream("GSOOffline.doors.json"))
                using (var r = new StreamReader(s))
                    doorData = Json.Deserialize<DoorFile>(r.ReadToEnd());
                return doorData;
            }
        }

        private void RegisterTravelHandlers()
        {
            On(4, 11, c => DepositItem((int)c[2], (int)c[3], (int)c[4]));
            On(4, 12, c => WithdrawItem((int)c[2], (int)c[3], (int)c[4]));
            On(3, 37, c => MoveBankSilver((int)c[2]));
        }

        /// <summary>Nearest client-side interactable of a type: the click only tells us the type.</summary>
        private Scr_Interactable NearestInteractable(int typeId)
        {
            var player = LocalPlayer;
            Scr_Interactable best = null;
            float bestDist = 15f;
            foreach (var i in Scr_Interactable.list)
            {
                if (i == null || i.typeId != typeId) continue;
                float d = Vector3.Distance(i.transform.position, player.transform.position);
                if (d < bestDist) { bestDist = d; best = i; }
            }
            return best;
        }

        /// <summary>Returns true if the interaction was a door/portal/bank handled here.</summary>
        private bool HandleTravelInteract(int typeId)
        {
            var player = LocalPlayer;
            if (player == null) return false;
            Vector3 p = player.transform.position;

            DoorDef door = null;
            float best = 15f;
            foreach (var d in Doors.doors)
            {
                if (d.type != typeId || d.scene != character.scene) continue;
                float dist = Vector3.Distance(V(d.pos), p);
                if (dist < best) { best = dist; door = d; }
            }
            if (door != null)
            {
                Teleport(door.toScene, V(door.toPos));
                return true;
            }

            switch (typeId)
            {
                case DoorInterior:
                    var interior = Doors.interiors.Find(i => i.scene == character.scene);
                    var spawn = interior != null ? Doors.interiorSpawns.Find(s => s.scene == interior.interior) : null;
                    if (spawn == null) return false;
                    PushReturnPoint(p);
                    Teleport(spawn.scene, V(spawn.pos));
                    return true;

                case DoorInteriorExit:
                    var clicked = NearestInteractable(typeId);
                    if (clicked != null && clicked.interactableName == "To Dungeon")
                    {
                        var dungeon = Doors.interiorSpawns.Find(s => s.scene == 24);
                        if (dungeon == null) return false;
                        PushReturnPoint(p);
                        Teleport(dungeon.scene, V(dungeon.pos));
                        return true;
                    }
                    ReturnToPreviousPoint();
                    return true;

                case DoorGeneric:
                    Notice("The door is locked.", "gray");
                    return true;

                case InteractChest:
                    var chest = NearestInteractable(typeId);
                    if (chest != null && chest.interactableName == "Bank chest")
                    {
                        OpenBank();
                        return true;
                    }
                    return false;
            }
            return false;
        }

        private void PushReturnPoint(Vector3 p)
        {
            character.returnPoints.Add(new ReturnPoint { scene = character.scene, x = p.x, y = p.y, z = p.z });
        }

        private void ReturnToPreviousPoint()
        {
            var rp = character.returnPoints;
            if (rp.Count > 0)
            {
                var last = rp[rp.Count - 1];
                rp.RemoveAt(rp.Count - 1);
                Teleport(last.scene, new Vector3(last.x, last.y, last.z));
                return;
            }
            // Entered without a recorded door (e.g. by wayshrine): go home.
            if (GameData.Wayshrines.TryGetValue(character.homeWayshrine, out var w)) Teleport(w.scene, w.pos);
        }

        private void UsePortal()
        {
            if (Doors.portal != null) Teleport(Doors.portal.scene, V(Doors.portal.pos));
        }

        // ---- bank ----------------------------------------------------------------------------

        private void OpenBank() => Send(3, 33, character.name, WindowBank);

        private void SendBank()
        {
            foreach (var it in character.bank)
                Send(2, 14, ItemDataString(it, it.amount), character.name);
        }

        private void DepositItem(int itemId, int typeId, int amount)
        {
            var t = ItemData.Get(typeId);
            var it = t?.Stacks == true ? FindStack(typeId) : FindItem(itemId);
            if (t == null || it == null) return;
            amount = Mathf.Clamp(amount, 1, it.amount);

            if (!t.Stacks)
            {
                if (it.equipped)
                {
                    it.equipped = false;
                    Send(3, 6, character.name, it.id);
                }
                character.items.Remove(it);
                Send(4, 3, character.name, it.id, it.typeId, 1);
                character.bank.Add(it);
                Send(2, 14, ItemDataString(it, 1), character.name);
                return;
            }
            RemoveFromStack(it, amount);
            var stack = character.bank.Find(b => b.typeId == typeId);
            if (stack == null)
            {
                stack = new ItemSave { id = character.nextItemId++, typeId = typeId, amount = 0, grade = t.baseGrade };
                character.bank.Add(stack);
            }
            stack.amount += amount;
            Send(2, 14, ItemDataString(stack, amount), character.name);
        }

        private void WithdrawItem(int itemId, int typeId, int amount)
        {
            var t = ItemData.Get(typeId);
            var it = character.bank.Find(b => t?.Stacks == true ? b.typeId == typeId : b.id == itemId);
            if (t == null || it == null) return;
            amount = Mathf.Clamp(amount, 1, it.amount);

            it.amount -= amount;
            if (it.amount <= 0) character.bank.Remove(it);
            Send(4, 13, character.name, it.id, typeId, amount);

            if (!t.Stacks)
            {
                it.amount = 1;
                character.items.Add(it);
                SendItemAdded(it, 1);
                CheckItemTriggers();
            }
            else
            {
                GiveItem(typeId, amount);
            }
        }

        private void MoveBankSilver(int amount)
        {
            if (amount > 0) amount = Mathf.Min(amount, character.silver);
            else amount = -Mathf.Min(-amount, character.bankSilver);
            if (amount == 0) return;
            character.bankSilver += amount;
            SetSilver(character.silver - amount);
            Send(25, 3, character.bankSilver);
        }
    }
}
